### ISSUE TITLE
Question about the definition of "boost" in paper

### ISSUE THREAD

**Issue by lewisjiang** [ibramjub/Fast-and-Accurate-Least-Mean-Squares-Solvers#1]
Dear authors, 

Thank you for open sourcing the code. I recently read your TPAMI [paper](https://ieeexplore.ieee.org/document/9677460/). In the experiments part, for example the linear regression case (fig 2.u), I find that you compare the runtime of 1) directly running LMS on raw data, with 2) running LMS on C-set. It is obvious that the latter one wins. But as you mentioned, calculating a C-set has the same complexity as directly solving LMS on raw data. So I'm wondering how can you "help improve existing solvers" if the time consumption between feeding raw data and getting the result is more of a concern? 

Hope to get your explanation. Thank you.

**Comment by ibramjub** [comment]
Hello,

That's a great question!
While the computational time of linear regression and our compression is theoretically the same, running linear regression on very large data may cause the computer to get stuck or crash, due to the high memory usage. However, computing our coreset in this case does not require the same amount of memory, and hence makes this computation feasible.
The lower memory usage is mainly due to our usage of the "merge and reduce technique", i.e., treating the huge data as a stream of  small data chunks, rather than a full chunk. Informally, this is done as follows: we compute the compression for the first small chunk, then we combine the obtained compression with the second chunk and compress again, etc.

Hope this answers your question.

**Comment by lewisjiang** [comment]
@ibramjub Thank you for the explanation, now I understand its appropriate use cases. Really nice work!
